name             'app_config'
maintainer       'Nathan L Smith'
maintainer_email 'nlloyds@gmail.com'
license          'apache2'
description      'Library for managing application configuration'
version          '0.1.0'
